# Generated by Django 2.2.6 on 2019-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
        ('core', '0003_pontoturistico_atracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comentario',
            field=models.ManyToManyField(to='comentario.Comentario'),
        ),
    ]
