# Generated by Django 2.2.6 on 2019-10-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('core', '0004_pontoturistico_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='avaliacao',
            field=models.ManyToManyField(to='avaliacao.Avaliacao'),
        ),
    ]
