# Generated by Django 2.2.6 on 2019-10-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191024_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docidentificacao',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
